/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_jni_JNIInit */

#ifndef _Included_com_tencent_jni_JNIInit
#define _Included_com_tencent_jni_JNIInit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_jni_JNIInit
 * Method:    changeLinearBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tencent_jni_JNIInit_changeLinearBuffer
  (JNIEnv *, jclass);

bool checkIsLinearAllocPtr_5m(long*);
#ifdef __cplusplus
}
#endif
#endif
